version: "3"
services:
  client:
    container_name: foodwar-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client/:/app
      - /app/node_modules
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # nginx:
  #   image: nginx:1.15-alpine11
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  server:
    container_name: foodwar-backend
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server/:/app
      - /app/node_modules
    environment:
      - NODE_PATH=src
      - PORT=4000
      - DB_HOST=mongo
      - DB=foodwar
    networks:
      - backend
    depends_on:
      - mongo
    ports:
      - "4000:4000"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
