version: "3"
services:
  client:
    container_name: foowar-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - "80:80"
    networks:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  # server:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #     - ./server/:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_PATH=src
  #     - PORT=4000
  #     - DB_HOST=mongo
  #     - DB=foodwar
  #   networks:
  #     - backend
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "4000:4000"
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   volumes:
  #     - data:/data/db
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - backend
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
