version: "3"
services:
  client:
    container_name: foodwar-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  server:
    container_name: foodwar-backend
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  data:
    driver: local
